In [14]:
import pandas as pd
final_input_table = pd.read_csv('./sungbin/9_02_final_4hours_input_table.csv')
final_input_table

,new_time,"('CAL_TIME_AVG', 50868)","('CAL_TIME_AVG', 50882)","('CAL_TIME_AVG', 50902)","('CAL_TIME_AVG', 50912)","('CAL_TIME_AVG', 50931)","('CAL_TIME_AVG', 50971)","('CAL_TIME_AVG', 50983)","('CAL_TIME_AVG', 51006)","('CAL_TIME_AVG', 51221)",...,"('CAL_TIME_AVG', 220051)","('CAL_TIME_AVG', 220179)","('CAL_TIME_AVG', 220180)","('CAL_TIME_AVG', 220210)","('CAL_TIME_AVG', 220277)","('CAL_TIME_AVG', 223761)",CAL_AGE,ETHNICITY,GENDER,class
0,200131_0,0.471049,0.513580,0.377083,0.000743,0.089646,0.243319,0.433908,0.103865,0.458012,...,NaN,0.488636,0.285706,0.088617,0.964391,0.937130,69.0,WHITE,F,0.0
1,200131_12,0.464789,0.488889,0.400000,0.000619,0.082219,0.284810,0.413793,0.108696,0.409474,...,NaN,0.499861,0.293929,0.089772,0.965176,0.935235,69.0,WHITE,F,0.0
2,200131_16,NaN,0.488889,0.412500,0.000866,0.073529,0.177215,NaN,0.081522,NaN,...,NaN,0.502681,0.294313,0.090274,0.964086,0.937562,69.0,WHITE,F,0.0
3,200131_20,0.450704,0.533333,0.412500,0.000743,0.086230,0.341772,0.448276,0.086957,0.429474,...,NaN,0.500145,0.291857,0.089525,0.964058,0.936814,69.0,WHITE,F,0.0
4,200131_4,0.460094,0.533333,0.395833,0.000619,0.075758,0.240506,0.454023,0.103261,0.378421,...,NaN,0.496292,0.289210,0.089242,0.964077,0.936722,69.0,WHITE,F,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9956,299931_12,0.464789,0.488889,0.412500,0.000990,0.094920,0.265823,0.448276,0.048913,0.347368,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0
9957,299931_16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.341053,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0
9958,299931_20,0.521127,0.511111,0.350000,0.001980,0.066845,0.177215,0.465517,0.228261,0.296316,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0
9959,299931_4,0.476526,0.488889,0.422917,0.001066,0.054144,0.285513,0.474138,0.062198,0.372281,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0
9960,299931_8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.381053,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0

In [13]:
#결손값 체크하기
length = len(final_input_table.iloc[:,1:-4].columns)
print(final_input_table.iloc[:,1:-4].notnull().sum(axis=1) / length , '\n')
drop_much_null = final_input_table[(final_input_table.iloc[:,1:-4].isnull().sum(axis=1) / length) < 0.8]

print(drop_much_null['class'].value_counts())
drop_much_null

0       0.888889
1       0.888889
2       0.666667
3       0.888889
4       0.888889
          ...
9956    0.555556
9957    0.055556
9958    0.555556
9959    0.555556
9960    0.111111
Length: 9961, dtype: float64

0.0    9533
1.0      64
Name: class, dtype: int64

,new_time,"('CAL_TIME_AVG', 50868)","('CAL_TIME_AVG', 50882)","('CAL_TIME_AVG', 50902)","('CAL_TIME_AVG', 50912)","('CAL_TIME_AVG', 50931)","('CAL_TIME_AVG', 50971)","('CAL_TIME_AVG', 50983)","('CAL_TIME_AVG', 51006)","('CAL_TIME_AVG', 51221)",...,"('CAL_TIME_AVG', 220051)","('CAL_TIME_AVG', 220179)","('CAL_TIME_AVG', 220180)","('CAL_TIME_AVG', 220210)","('CAL_TIME_AVG', 220277)","('CAL_TIME_AVG', 223761)",CAL_AGE,ETHNICITY,GENDER,class
0,200131_0,0.471049,0.513580,0.377083,0.000743,0.089646,0.243319,0.433908,0.103865,0.458012,...,NaN,0.488636,0.285706,0.088617,0.964391,0.937130,69.0,WHITE,F,0.0
1,200131_12,0.464789,0.488889,0.400000,0.000619,0.082219,0.284810,0.413793,0.108696,0.409474,...,NaN,0.499861,0.293929,0.089772,0.965176,0.935235,69.0,WHITE,F,0.0
2,200131_16,NaN,0.488889,0.412500,0.000866,0.073529,0.177215,NaN,0.081522,NaN,...,NaN,0.502681,0.294313,0.090274,0.964086,0.937562,69.0,WHITE,F,0.0
3,200131_20,0.450704,0.533333,0.412500,0.000743,0.086230,0.341772,0.448276,0.086957,0.429474,...,NaN,0.500145,0.291857,0.089525,0.964058,0.936814,69.0,WHITE,F,0.0
4,200131_4,0.460094,0.533333,0.395833,0.000619,0.075758,0.240506,0.454023,0.103261,0.378421,...,NaN,0.496292,0.289210,0.089242,0.964077,0.936722,69.0,WHITE,F,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9954,299901_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.491723,0.288251,0.088553,0.964426,0.934264,81.0,WHITE,F,0.0
9955,299931_0,0.450704,0.488889,0.450000,0.001671,0.059158,0.234177,0.482759,0.214674,0.305965,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0
9956,299931_12,0.464789,0.488889,0.412500,0.000990,0.094920,0.265823,0.448276,0.048913,0.347368,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0
9958,299931_20,0.521127,0.511111,0.350000,0.001980,0.066845,0.177215,0.465517,0.228261,0.296316,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0
9959,299931_4,0.476526,0.488889,0.422917,0.001066,0.054144,0.285513,0.474138,0.062198,0.372281,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,WHITE,M,0.0

In [7]:

no_miss = pd.read_csv('./sungbin/9_2_final_4hour_check.csv')
no_miss

,new_time,"('CAL_TIME_AVG', 50868)","('CAL_TIME_AVG', 50882)","('CAL_TIME_AVG', 50902)","('CAL_TIME_AVG', 50912)","('CAL_TIME_AVG', 50931)","('CAL_TIME_AVG', 50971)","('CAL_TIME_AVG', 50983)","('CAL_TIME_AVG', 51006)","('CAL_TIME_AVG', 51221)",...,"('CAL_TIME_AVG', 220180)","('CAL_TIME_AVG', 220210)","('CAL_TIME_AVG', 220277)","('CAL_TIME_AVG', 223761)",CAL_AGE,ETHNICITY,GENDER,class,renew_time,ICU
0,200131_0,0.471049,0.513580,0.377083,0.000743,0.089646,0.243319,0.433908,0.103865,0.458012,...,0.285706,0.088617,0.964391,0.937130,69.0,WHITE,F,0.0,2001310000,200131
1,200131_4,0.460094,0.533333,0.395833,0.000619,0.075758,0.240506,0.454023,0.103261,0.378421,...,0.289210,0.089242,0.964077,0.936722,69.0,WHITE,F,0.0,2001310004,200131
2,200131_8,0.492235,0.444214,0.423674,0.000495,0.083915,0.291981,0.460907,0.081522,0.517895,...,0.293942,0.090569,0.963677,0.934769,69.0,WHITE,F,0.0,2001310008,200131
3,200131_12,0.464789,0.488889,0.400000,0.000619,0.082219,0.284810,0.413793,0.108696,0.409474,...,0.293929,0.089772,0.965176,0.935235,69.0,WHITE,F,0.0,2001310012,200131
4,200131_16,0.492235,0.488889,0.412500,0.000866,0.073529,0.177215,0.460907,0.081522,0.397624,...,0.294313,0.090274,0.964086,0.937562,69.0,WHITE,F,0.0,2001310016,200131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9542,299901_0,0.492235,0.444214,0.423674,0.001893,0.083915,0.291981,0.460907,0.169862,0.397624,...,0.288251,0.088553,0.964426,0.934264,81.0,WHITE,F,0.0,2999010000,299901
9543,299931_0,0.450704,0.488889,0.450000,0.001671,0.059158,0.234177,0.482759,0.214674,0.305965,...,0.291341,0.089642,0.964246,0.936291,65.0,WHITE,M,0.0,2999310000,299931
9544,299931_8,0.492235,0.444214,0.423674,0.001893,0.083915,0.291981,0.460907,0.169862,0.381053,...,0.291341,0.089642,0.964246,0.936291,65.0,WHITE,M,0.0,2999310008,299931
9545,299931_12,0.464789,0.488889,0.412500,0.000990,0.094920,0.265823,0.448276,0.048913,0.347368,...,0.291341,0.089642,0.964246,0.936291,65.0,WHITE,M,0.0,2999310012,299931
9546,299931_20,0.521127,0.511111,0.350000,0.001980,0.066845,0.177215,0.465517,0.228261,0.296316,...,0.291341,0.089642,0.964246,0.936291,65.0,WHITE,M,0.0,2999310020,299931

In [8]:
no_miss['class'].value_counts()

0.0    9487
1.0      60
Name: class, dtype: int64